#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/openvswitch-vtep" ]; then
	if [ ! -e "/etc/init/openvswitch-vtep.conf" ]; then
		update-rc.d openvswitch-vtep defaults >/dev/null
	fi
	if [ -n "$2" ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	invoke-rc.d openvswitch-vtep $_dh_action || exit $?
fi
# End automatically added section
