#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/openvswitch-vtep" ] && [ "$1" = remove ]; then
	invoke-rc.d openvswitch-vtep stop || exit $?
fi
# End automatically added section
